// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2XTm7aa4vVZhyfppICBzVXipkYOA2mrM',
    appId: '1:378751422000:web:2d05eb2cbc55d6546e27f5',
    messagingSenderId: '378751422000',
    projectId: 'gombak-runner',
    authDomain: 'gombak-runner.firebaseapp.com',
    databaseURL: 'https://gombak-runner-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gombak-runner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyHR-z6vty37zHSWD_jjdgvG1ScEelinI',
    appId: '1:378751422000:android:b2fcad38c0285c9e6e27f5',
    messagingSenderId: '378751422000',
    projectId: 'gombak-runner',
    databaseURL: 'https://gombak-runner-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gombak-runner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnnqVH7MO_uAlN_j5AtxTbmPvfEGDaszM',
    appId: '1:378751422000:ios:940e98043228fcd56e27f5',
    messagingSenderId: '378751422000',
    projectId: 'gombak-runner',
    databaseURL: 'https://gombak-runner-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gombak-runner.firebasestorage.app',
    iosBundleId: 'com.freshbunny.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnnqVH7MO_uAlN_j5AtxTbmPvfEGDaszM',
    appId: '1:378751422000:ios:940e98043228fcd56e27f5',
    messagingSenderId: '378751422000',
    projectId: 'gombak-runner',
    databaseURL: 'https://gombak-runner-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gombak-runner.firebasestorage.app',
    iosBundleId: 'com.freshbunny.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2XTm7aa4vVZhyfppICBzVXipkYOA2mrM',
    appId: '1:378751422000:web:8706cd5eccb6b3fd6e27f5',
    messagingSenderId: '378751422000',
    projectId: 'gombak-runner',
    authDomain: 'gombak-runner.firebaseapp.com',
    databaseURL: 'https://gombak-runner-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gombak-runner.firebasestorage.app',
  );

}